apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: test-fail-kustomize
  namespace: default
spec:
  interval: 1m
  path: ./not-exist-folder    # 🚫 Path qui n'existe pas
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  timeout: 1m