apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: test-fail-helm
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: nginx
      version: "999.999.999"    # 🚫 Version qui n'existe pas
      sourceRef:
        kind: HelmRepository
        name: bitnami           # 🚫 Repo qui n'existe pas encore
        namespace: flux-system
  values:
    service:
      type: ClusterIP  
    resources:
      limits:
        memory: 128Mi
        cpu: 100m